phpsupport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
]

service/urls.py
from django.urls import path
from .views import view_index, view_freelancer_orders

app_name = 'service'

urlpatterns = [
    path('', view_index, name='index'),
    path('freelancer_orders/', view_freelancer_orders, name='freelancer_orders')
]

users/urls.py
from django.urls import path
from .views import login

app_name = 'users'

urlpatterns = [
    path('sign-in', login, name='sign-in')
]

service/models.py
from django.db import models
from users.models import Customer, Freelancer


class Order(models.Model):
    status_choices = [
        ('1 not processed', 'Необработан'),
        ('2 selected', 'Выбран фрилансер'),
        ('3 performed', 'В работе'),
        ('4 completed', 'Выполнен'),
        ('5 expired', 'Просрочен')
    ]
    title = models.CharField(
        'Название заказа',
        max_length=300,
        blank=True
    )
    client = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name='client_orders',
        verbose_name='Клиент',
    )
    freelancer = models.ForeignKey(
        Freelancer,
        on_delete=models.CASCADE,
        related_name='freelancer_orders',
        verbose_name='Фрилансер',
        null=True,
        blank=True
    )
    description = models.TextField(
        verbose_name='Описание заказа',
        max_length=100,
        null=True,
        blank=True
    )
    status = models.CharField(
        verbose_name='Статус',
        choices=status_choices,
        default='1 not processed',
        db_index=True,
        max_length=30,
    )
    created_at = models.DateTimeField(
        verbose_name='Время создания',
        auto_now_add=True
    )
    deadline = models.DateTimeField(
        verbose_name='Срок выполнения',
        null=True,
        blank=True
    )
    messages = models.TextField(
        verbose_name='Переписка по заказу',
        default=f'Переписка по заказу',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'{self.client}_{self.freelancer}_{self.created_at}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator


class BotState(models.Model):
    telegram_id = models.IntegerField(
        'Telegram Id',
    )
    bot_state = models.CharField(
        'Текущее состояние бота',
        max_length=100,
        help_text="Стейт-машина бота"
    )


class User(AbstractUser):
    telegram_id = models.IntegerField(
        'Telegram Id',
        null=True,
        blank=True
    )
    phone_number = PhoneNumberField(
        verbose_name='Телефон',
        region='RU',
        null=True,
        blank=True
    )
    bot_state = models.CharField(
        'Текущее состояние бота',
        max_length=100,
        blank=True,
        help_text="Стейт-машина бота"
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

class Customer(User):
    status_choices = [
        ('no status', 'Нет подписки'),
        ('economy', 'Эконом'),
        ('base', 'Базовый'),
        ('vip', 'VIP'),
    ]

    status = models.CharField(
        verbose_name='Статус',
        choices=status_choices,
        default='no status',
        db_index=True,
        max_length=30,
    )
    payment_status = models.BooleanField(
        verbose_name='Статус оплаты',
        default=False
    )

    class Meta:
        verbose_name = 'Заказчик'
        verbose_name_plural = 'Заказчики'

class Freelancer(User):
    rating = models.IntegerField(
        'Рейтинг',
        validators=[MaxValueValidator(100),],
        default=100
    )

    class Meta:
        verbose_name = 'Фрилансер'
        verbose_name_plural = 'Фрилансеры'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите никнейм', 'id':' floatingInput'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль', 'id':' floatingPassword'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

service/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Order
from users.models import Freelancer


@login_required(login_url='users:sign-in')
def view_index(request):
    orders = Order.objects.all()
    processed_orders = []
    for order in orders:
        order_attr_for_managers = {
            'id': order.id,
            'title': order.title,
            'customer': order.client,
            'freelancer': order.freelancer,
            'status': order.get_status_display(),
            'created_at': order.created_at,
            'deadline': order.deadline
        }  
        processed_orders.append(order_attr_for_managers)

    return render(request, 'service/index.html', context={
        'processed_orders': processed_orders
    })


@login_required(login_url='users:sign-in')
def view_freelancer_orders(request):
    freelancers = Freelancer.objects.all()
    freelancer_orders = []
    for freelancer in freelancers:
        freelancer_attrs = {
            'username': freelancer.username,
            'orders': len(freelancer.freelancer_orders.all()),
            'phone_number': freelancer.phone_number,
            'rating': freelancer.rating
        }
        freelancer_orders.append(freelancer_attrs)
    
    return render(request, 'service/freelancer_orders.html', context={
        'freelancer_orders': freelancer_orders
    })

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .forms import UserLoginForm
from django.contrib import auth


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active and user.is_staff:
                auth.login(request, user)

                return HttpResponseRedirect(reverse('service:index'))
    else:
        form = UserLoginForm()

    context = {
        'form': form
    }

    return render(request, 'users/login.html', context)

templates/service/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Заказы</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<body>
    <div class="container">
        <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
              <li class="nav-item"><a href="{% url 'service:index' %}" class="nav-link">Главная</a></li>
              <li class="nav-item"><a href="{% url 'service:freelancer_orders' %}" class="nav-link">Фрилансеры</a></li>
            </ul>
          </header>
        {% block content%}
    {% endblock %}
    </div>
</body>
</html>

templates/service/freelancer_orders.html
{% extends 'service/base.html' %}
{% load static%}
{% block content %}
<ul class="list-group text-center">
  {% for freelancer_order in freelancer_orders%}
    <li class="list-group-item">Никнейм фрилансера - {{freelancer_order.username}} | 
      Количество заказов в работе - {{freelancer_order.orders}} | 
      Номер телефона - {{freelancer_order.phone_number}} | 
      Рейтинг - {{freelancer_order.rating}}
    </li>
    <hr>
  {% endfor %}
</ul>
{% endblock %}

templates/service/index.html
{% extends 'service/base.html' %}
{% load static%}
{% block content%}
    <table class="table table-responsive">
        <tr>
            <th>ID заказа</th>
            <th>Название заказа</th>
            <th>Заказчик</th>
            <th>Фрилансер</th>
            <th>Статус заказа</th>
            <th>Заказ создан</th>
            <th>Дедлайн</th>
        </tr>
        {% for order in processed_orders%}
        <tr>
            <td>{{order.id}}</td>
            <td>{{order.title}}</td>
            <td>{{order.customer}}</td>
            <td>{{order.freelancer}}</td>
            <td>{{order.status}}</td>
            <td>{{order.created_at}}</td>
            <td>{{order.deadline}}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock%}

templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Войти</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel='stylesheet' href="{% static 'css/sign-in.css' %}">
</head>
<body>
    <main class="form-signin w-100 m-auto">
      {% if form.errors or messages %}
      <div class="alert {% if messages%} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
              style="margin-top: 50px;">
              {% if messages %}
                  {% for message in messages%}
                      {{ message }}
                  {% endfor %}
              {% else %}
                  {{form.non_field_errors}}
              {% endif %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
      {% endif %}
        <form method='post'>
          {% csrf_token %}
          <svg xmlns="http://www.w3.org/2000/svg" width="72" height="57" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16" style='margin-left:110px;'>
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
          </svg>
          </a>
          <h1 class="h3 mb-4 fw-normal" style='margin-left:110px;margin-top:20px;'>Вход</h1>
      
          <div class="form-floating" style='margin-bottom: 20px;'>
            {{ form.username }}
            <label for="floatingInput">Никнейм</label>
          </div>
          <div class="form-floating">
            {{ form.password }}
            <label for="floatingPassword">Пароль</label>
          </div>
      
          <button class="w-100 btn btn-lg btn-primary" type="submit">Вход</button>
        </form>
      </main>
</body>
</html>